"""
This type stub file was generated by pyright.
"""

def base64_encode_image(a): # -> str:
	...

def base64_decode_image(a): # -> ndarray[Any, dtype[float64]]:
	...

def base64_encode_array(a): # -> bytes:
	...

def base64_decode_array(a, dtype): # -> NDArray[float64]:
	...

