"""
This type stub file was generated by pyright.
"""

image_types = ...
def list_images(basePath, contains=...): # -> Generator[Any, Any, None]:
    ...

def list_files(basePath, validExts=..., contains=...): # -> Generator[Any, Any, None]:
    ...

