"""
This type stub file was generated by pyright.
"""


"""
Transformation Based Learning

A general purpose package for Transformation Based Learning,
currently used by nltk.tag.BrillTagger.

isort:skip_file
"""
