---
exclude: ^democracy_exe/alembic/.*
# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
ci:
  autofix_commit_msg: 'style: pre-commit fixes'
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: 'chore: update pre-commit hooks'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
default_install_hook_types:
  # is triggered before the commit is finalized to allow checks on the code being committed. Running hooks on unstaged changes can lead to both false-positives and false-negatives during committing. pre-commit only runs on the staged contents of files by temporarily stashing the unstaged changes while running hooks.
  - pre-commit
  # hooks will be passed a single filename -- this file contains the current contents of the commit message to be validated. The commit will be aborted if there is a nonzero exit code.
  - commit-msg
  # pre-push is triggered on git push.
  - pre-push
default_stages:
  - pre-commit
  - pre-push
# TODO: Work with team to see when the right time is to enable this
# # exclude: '^validate_pyproject/_vendor'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Simply check whether files parse as valid python.
      - id: check-ast
        exclude: (.vscode|contrib)
      - id: check-json
        exclude: (.vscode|.devcontainer|hack|cookbook|ai_docs)

  # When running with --fix, Ruff's lint hook should be placed before Ruff's formatter hook, and before Black, isort, and other formatting tools, as Ruff's fix behavior can output code changes that require reformatting.
  # SOURCE: https://github.com/astral-sh/ruff-pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      # Run the linter.
      - id: ruff
        # entry: ruff check --force-exclude
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --show-fixes
          - --config=pyproject.toml
        # SOURCE: https://github.com/girder/large_image/blob/2e6fd90cfb9179f2c0bd59031f45805018f3f04a/.pre-commit-config.yaml
        types_or:
          - python
          # - jupyter
        exclude: ^(scripts|typings)/.*

      # Run the formatter.
      - id: ruff-format
        # entry: ruff format --force-exclude
        types_or:
          - python
          # - jupyter
        args:
          - --config=pyproject.toml
        files: ^((src|tests|notebooks)/.+)?[^/]+\.(py|ipynb)$
        exclude: (.tasks|hack|scripts)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
        exclude: (.*\.pyi$)
      - id: mixed-line-ending
        exclude: (.*\.pyi$)
      - id: trailing-whitespace
        exclude: (.*\.pyi$)
  ##########################################################################################
  # #  # NOTE: if we are going to use this, it needs to run AFTER ruff.
  ##########################################################################################

  # SOURCE:https://github.com/humblFINANCE/humblAPI/blob/master/.pre-commit-config.yaml
  # SOURCE: https://github.com/pypa/pip/blob/main/.pre-commit-config.yaml
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-log-warn
      - id: text-unicode-replacement-char

  # NOTE: This requires you to brew install taplo
  - repo: local
    hooks:
  #     - id: taplo-lint
  #       name: taplo
  #       entry: taplo lint  --config taplo.toml --schema=https://json.schemastore.org/pyproject.json pyproject.toml
  #       language: system
  #       types:
  #         - toml
  #       files: ^pyproject.*$
  #     - id: taplo-format
  #       name: taplo
  #       entry: taplo format --config taplo.toml
  #       language: system
  #       types:
  #         - toml
  #       files: ^pyproject.*$
      - id: detect-pytest-live-log
        name: detect-pytest-live-log
        entry: bash -x ./detect_pytest_live_logging.sh
        language: system
        types:
          - toml
        files: ^pyproject.*$

  # SOURCE: https://github.com/3MAH/microgen/blob/0a7b86ccffb6a904443049e475c1c571a94addb5/.pre-commit-config.yaml#L42
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        args:
          - --style {numpydoc,pep257}
          - --no-strip-whitespace
          - --no-capitalize-first-letter
        files: ^((src|tests|notebooks)/.+)?[^/]+\.(py|ipynb)$
        exclude: (.tasks|hack)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
          - --keep-runtime-typing
  - repo: https://github.com/twisted/towncrier
    rev: 24.8.0  # run 'pre-commit autoupdate' to update
    hooks:
      - id: towncrier-update
        files: $changelog\.d/
        args:
          - --keep

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.7
    hooks:
      - id: fix-smartquotes
  # - repo: https://github.com/lyz-code/yamlfix
  #   rev: 1.17.0
  #   hooks:
  #     - id: yamlfix
  #       args:
  #         - -c
  #         - pyproject.toml
  #       exclude: .*cassettes.*
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:

      - id: check-github-workflows
        exclude: (.tasks|hack|.github/workflows/_python-vulnerability-scan.yml)
      - id: check-readthedocs

  # SOURCE: https://github.com/kiwicom/pytest-recording/tree/master
  - repo: https://github.com/codingjoe/relint
    rev: 3.3.1
    hooks:
      - id: relint
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier


# - repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.8.5
  #   hooks:
  #   - id: nbqa-check-ast
  #     name: validate Python notebooks
  #   - id: nbqa-ruff
  #     name: ruff for notebooks (see https://docs.astral.sh/ruff/rules)
  #     args: [--fix, '--select=A,ARG,B,BLE,C,C4,E,F,FLY,I,INT,ISC,PERF,PIE,PLC,PLE,PYI,Q003,RET,RSE,SIM,TID,TRY,UP,W', '--ignore=B007,B008,B015,B018,E402,E501,E741,PLC2401,PLC2403,SIM114']
