version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: documentation/conf.py

formats:
   - pdf
   - epub

python:
   install:
   - requirements: documentation/requirements.txt
