"""
This type stub file was generated by pyright.
"""

from packaging import version
from aider._version import __version__

__version__ = ...
safe_version = ...
if type(__version__) is not str:
    __version__ = ...
else:
    ...
__all__ = [__version__]
