"""
This type stub file was generated by pyright.
"""

import argparse

class DotEnvFormatter(argparse.HelpFormatter):
    def start_section(self, heading): # -> None:
        ...
    


class YamlHelpFormatter(argparse.HelpFormatter):
    def start_section(self, heading): # -> None:
        ...
    


class MarkdownHelpFormatter(argparse.HelpFormatter):
    def start_section(self, heading): # -> None:
        ...
    


