"""
This type stub file was generated by pyright.
"""

def default_env_file(git_root): # -> str:
    ...

def get_parser(default_config_files, git_root): # -> ArgumentParser:
    ...

def get_md_help(): # -> str:
    ...

def get_sample_yaml(): # -> str:
    ...

def get_sample_dotenv(): # -> str:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    status = ...
