"""
This type stub file was generated by pyright.
"""

class ClipboardWatcher:
    """Watches clipboard for changes and updates IO placeholder"""
    def __init__(self, io, verbose=...) -> None:
        ...
    
    def start(self): # -> None:
        """Start watching clipboard for changes"""
        ...
    
    def stop(self): # -> None:
        """Stop watching clipboard for changes"""
        ...
    


def main(): # -> None:
    """Example usage of the clipboard watcher"""
    ...

if __name__ == "__main__":
    ...
