"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass
class ExInfo:
    name: str
    retry: bool
    description: str
    ...


EXCEPTIONS = ...
class LiteLLMExceptions:
    exceptions = ...
    def __init__(self) -> None:
        ...
    
    def exceptions_tuple(self): # -> tuple[Any, ...]:
        ...
    
    def get_ex_info(self, ex): # -> ExInfo:
        """Return the ExInfo for a given exception instance"""
        ...
    


