"""
This type stub file was generated by pyright.
"""

def install_help_extra(io): # -> Literal[True] | None:
    ...

def get_package_files(): # -> Generator[Traversable | Any, Any, None]:
    ...

def fname_to_url(filepath): # -> str:
    ...

def get_index():
    ...

class Help:
    def __init__(self) -> None:
        ...
    
    def ask(self, question): # -> str:
        ...
    


