"""
This type stub file was generated by pyright.
"""

class ChatSummary:
    def __init__(self, models=..., max_tokens=...) -> None:
        ...
    
    def too_big(self, messages): # -> bool:
        ...
    
    def tokenize(self, messages): # -> list[Any]:
        ...
    
    def summarize(self, messages, depth=...): # -> list[dict[str, str]]:
        ...
    
    def summarize_all(self, messages): # -> list[dict[str, str]]:
        ...
    


def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
