"""
This type stub file was generated by pyright.
"""

FENCE = ...
def get_python_info(): # -> str:
    ...

def get_os_info(): # -> str:
    ...

def get_git_info(): # -> str:
    ...

def report_github_issue(issue_text, title=..., confirm=...): # -> None:
    """
    Compose a URL to open a new GitHub issue with the given text prefilled,
    and attempt to launch it in the default web browser.

    :param issue_text: The text of the issue to file
    :param title: The title of the issue (optional)
    :param confirm: Whether to ask for confirmation before opening the browser (default: True)
    :return: None
    """
    ...

def exception_handler(exc_type, exc_value, exc_traceback): # -> None:
    ...

def report_uncaught_exceptions(): # -> None:
    """
    Set up the global exception handler to report uncaught exceptions.
    """
    ...

def dummy_function1(): # -> None:
    ...

def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
