"""
This type stub file was generated by pyright.
"""

def run_cmd(command, verbose=..., error_print=..., cwd=...): # -> tuple[bool | None, str] | tuple[Literal[1], str] | tuple[int | Any, LiteralString]:
    ...

def get_windows_parent_process_name(): # -> str | None:
    ...

def run_cmd_subprocess(command, verbose=..., cwd=..., encoding=...): # -> tuple[int | Any, LiteralString] | tuple[Literal[1], str]:
    ...

def run_cmd_pexpect(command, verbose=..., cwd=...): # -> tuple[bool | None, str] | tuple[Literal[1], str]:
    """
    Run a shell command interactively using pexpect, capturing all output.

    :param command: The command to run as a string.
    :param verbose: If True, print output in real-time.
    :return: A tuple containing (exit_status, output)
    """
    ...

