"""
This type stub file was generated by pyright.
"""

ROOT_IMPORTANT_FILES = ...
NORMALIZED_ROOT_IMPORTANT_FILES = ...
def is_important(file_path): # -> bool:
    ...

def filter_important_files(file_paths): # -> list[Any]:
    """
    Filter a list of file paths to return only those that are commonly important in codebases.

    :param file_paths: List of file paths to check
    :return: List of file paths that match important file patterns
    """
    ...

