"""
This type stub file was generated by pyright.
"""

VERSION_CHECK_FNAME = ...
def install_from_main_branch(io): # -> Literal[True] | None:
    """
    Install the latest version of aider from the main branch of the GitHub repository.
    """
    ...

def install_upgrade(io, latest_version=...): # -> Literal[True] | None:
    """
    Install the latest version of aider from PyPI.
    """
    ...

def check_version(io, just_check=..., verbose=...): # -> bool | None:
    ...

