"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional
from pathspec import PathSpec

def load_gitignores(gitignore_paths: list[Path]) -> Optional[PathSpec]:
    """Load and parse multiple .gitignore files into a single PathSpec"""
    ...

class FileWatcher:
    """Watches source files for changes and AI comments"""
    ai_comment_pattern = ...
    def __init__(self, coder, gitignores=..., verbose=..., analytics=..., root=...) -> None:
        ...
    
    def filter_func(self, change_type, path): # -> bool | None:
        """Filter function for the file watcher"""
        ...
    
    def start(self): # -> None:
        """Start watching for file changes"""
        ...
    
    def stop(self): # -> None:
        """Stop watching for file changes"""
        ...
    
    def process_changes(self): # -> str:
        """Get any detected file changes"""
        ...
    
    def get_ai_comments(self, filepath): # -> tuple[None, None, None] | tuple[list[Any], list[Any], Literal['!', '?'] | None]:
        """Extract AI comment line numbers, comments and action status from a file"""
        ...
    


def main(): # -> None:
    """Example usage of the file watcher"""
    ...

if __name__ == "__main__":
    ...
