# pyright: reportUnusedFunction=false
from __future__ import annotations

import sys

from typing import Dict, List, NoReturn

from democracy_exe.utils.ai_docs_utils.api import (
    BASIC_DOCS_SYSTEM_PROMPT,
    REFINED_DOCS_FOLLOW_UP_PROMPT,
    arequest_message,
    check_prompt_token_size,
    read_file,
    request_message,
)
from democracy_exe.utils.ai_docs_utils.extract_repo import extract_local_directory


SIGNATURE = """
> [!NOTE]
> Documentation auto-generated by [ai-docs.](https://github.com/connor-john/ai-docs)

"""


async def _extend_docs(repo_name: str, messages: list[dict[str, str]], message: str) -> None:
    """Prompt further to refine the documentation for niche insights.

    Args:
        repo_name: Name of the repository
        messages: List of message dictionaries containing role and content
        message: Current documentation message to extend
    """
    messages.extend(
        [
            {"role": "assistant", "content": message},
            {"role": "user", "content": REFINED_DOCS_FOLLOW_UP_PROMPT},
        ]
    )
    response = await arequest_message(BASIC_DOCS_SYSTEM_PROMPT, messages)

    message = response.content[0].text
    with open(f"{repo_name}-further-docs.md", "w", encoding="utf-8") as file:
        file.write(message)


async def agenerate_docs_from_local_repo(directory_path: str) -> None:
    """Generate docs for the provided repo using Claude Opus.

    Args:
        directory_path: Path to the local repository directory
    """
    code_file_path = extract_local_directory(directory_path)
    file_content = read_file(code_file_path)
    input_prompt = f"Given this repo. \n{file_content}\ncomplete your instruction"

    messages = [
        {"role": "user", "content": input_prompt},
    ]
    response = await arequest_message(BASIC_DOCS_SYSTEM_PROMPT, messages)

    message = response.content[0].text
    readme_text = SIGNATURE + message
    readme_path = f"{directory_path}/README.md"
    with open(readme_path, "w", encoding="utf-8") as file:
        file.write(readme_text)


def generate_docs_from_local_repo(directory_path: str) -> None:
    """Generate docs for the provided repo using Claude Opus.

    Args:
        directory_path: Path to the local repository directory
    """
    code_file_path = extract_local_directory(directory_path)
    file_content = read_file(code_file_path)
    input_prompt = f"Given this repo. \n{file_content}\ncomplete your instruction"

    messages = [
        {"role": "user", "content": input_prompt},
    ]
    response = request_message(BASIC_DOCS_SYSTEM_PROMPT, messages)

    message = response.content[0].text
    readme_text = SIGNATURE + message
    readme_path = f"{directory_path}/README.md"
    with open(readme_path, "w", encoding="utf-8") as file:
        file.write(readme_text)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python generate_docs.py <local repository directory>")
        sys.exit(1)

    directory_path = sys.argv[1]
    generate_docs_from_local_repo(directory_path)
