"""
This type stub file was generated by pyright.
"""

from typing import List, Literal, Optional, TYPE_CHECKING, TypedDict
from typing_extensions import NotRequired
from .snowflake import Snowflake
from .user import User
from .emoji import PartialEmoji

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
LayoutType = Literal[1]
class PollMedia(TypedDict):
    text: str
    emoji: NotRequired[Optional[PartialEmoji]]
    ...


class PollAnswer(TypedDict):
    poll_media: PollMedia
    ...


class PollAnswerWithID(PollAnswer):
    answer_id: int
    ...


class PollAnswerCount(TypedDict):
    id: Snowflake
    count: int
    me_voted: bool
    ...


class PollAnswerVoters(TypedDict):
    users: List[User]
    ...


class PollResult(TypedDict):
    is_finalized: bool
    answer_counts: List[PollAnswerCount]
    ...


class PollCreate(TypedDict):
    allow_multiselect: bool
    answers: List[PollAnswer]
    duration: float
    layout_type: LayoutType
    question: PollMedia
    ...


class Poll(TypedDict):
    allow_multiselect: bool
    answers: List[PollAnswerWithID]
    expiry: str
    layout_type: LayoutType
    question: PollMedia
    results: PollResult
    ...


