"""
This type stub file was generated by pyright.
"""

from typing import Literal, Optional, TypedDict
from typing_extensions import NotRequired

"""
This type stub file was generated by pyright.
"""
class SKU(TypedDict):
    id: str
    type: int
    application_id: str
    name: str
    slug: str
    flags: int
    ...


class Entitlement(TypedDict):
    id: str
    sku_id: str
    application_id: str
    user_id: Optional[str]
    type: int
    deleted: bool
    starts_at: NotRequired[str]
    ends_at: NotRequired[str]
    guild_id: NotRequired[str]
    consumed: NotRequired[bool]
    ...


EntitlementOwnerType = Literal[1, 2]
