"""
This type stub file was generated by pyright.
"""

from typing import List, Union

"""
This type stub file was generated by pyright.
"""
Snowflake = Union[str, int]
SnowflakeList = List[Snowflake]
