"""
This type stub file was generated by pyright.
"""

from typing import List, Literal, Optional, TypedDict
from .user import PartialUser
from .snowflake import Snowflake

"""
This type stub file was generated by pyright.
"""
class TeamMember(TypedDict):
    user: PartialUser
    membership_state: int
    permissions: List[str]
    team_id: Snowflake
    role: Literal['admin', 'developer', 'read_only']
    ...


class Team(TypedDict):
    id: Snowflake
    name: str
    owner_id: Snowflake
    members: List[TeamMember]
    icon: Optional[str]
    ...


