"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, TypedDict
from .snowflake import Snowflake

"""
This type stub file was generated by pyright.
"""
class WelcomeScreen(TypedDict):
    description: str
    welcome_channels: List[WelcomeScreenChannel]
    ...


class WelcomeScreenChannel(TypedDict):
    channel_id: Snowflake
    description: str
    emoji_id: Optional[Snowflake]
    emoji_name: Optional[str]
    ...


