"""
This type stub file was generated by pyright.
"""

def should_colorize(stream): # -> bool:
    ...

def should_wrap(stream): # -> Literal[False]:
    ...

def wrap(stream): # -> StreamWrapper:
    ...

