"""
This type stub file was generated by pyright.
"""

from datetime import datetime as datetime_

tokens = ...
pattern = ...
class datetime(datetime_):
    def __format__(self, fmt): # -> LiteralString:
        ...
    


def aware_now(): # -> datetime:
    ...

