"""
This type stub file was generated by pyright.
"""

def filter_none(record): # -> bool:
    ...

def filter_by_name(record, parent, length): # -> Literal[False]:
    ...

def filter_by_level(record, level_per_module): # -> bool:
    ...

