"""
This type stub file was generated by pyright.
"""

def generate_rename_path(root, ext, creation_time): # -> str:
    ...

class FileDateFormatter:
    def __init__(self, datetime=...) -> None:
        ...
    
    def __format__(self, spec): # -> LiteralString:
        ...
    


class Compression:
    @staticmethod
    def add_compress(path_in, path_out, opener, **kwargs): # -> None:
        ...
    
    @staticmethod
    def write_compress(path_in, path_out, opener, **kwargs): # -> None:
        ...
    
    @staticmethod
    def copy_compress(path_in, path_out, opener, **kwargs): # -> None:
        ...
    
    @staticmethod
    def compression(path_in, ext, compress_function): # -> None:
        ...
    


class Retention:
    @staticmethod
    def retention_count(logs, number): # -> None:
        ...
    
    @staticmethod
    def retention_age(logs, seconds): # -> None:
        ...
    


class Rotation:
    @staticmethod
    def forward_day(t):
        ...
    
    @staticmethod
    def forward_weekday(t, weekday):
        ...
    
    @staticmethod
    def forward_interval(t, interval):
        ...
    
    @staticmethod
    def rotation_size(message, file, size_limit):
        ...
    
    class RotationTime:
        def __init__(self, step_forward, time_init=...) -> None:
            ...
        
        def __call__(self, message, file): # -> bool:
            ...
        
    
    


class FileSink:
    def __init__(self, path, *, rotation=..., retention=..., compression=..., delay=..., watch=..., mode=..., buffering=..., encoding=..., **kwargs) -> None:
        ...
    
    def write(self, message): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def tasks_to_complete(self): # -> list[Any]:
        ...
    


