"""
This type stub file was generated by pyright.
"""

def get_frame_fallback(n): # -> FrameType | None:
    ...

def load_get_frame_function(): # -> Callable[[int], FrameType] | Callable[..., FrameType | None]:
    ...

get_frame = ...
