"""
This type stub file was generated by pyright.
"""

import os

if not hasattr(os, "register_at_fork"):
    def create_logger_lock(): # -> Lock:
        ...
    
    def create_handler_lock(): # -> Lock:
        ...
    
else:
    logger_locks = ...
    handler_locks = ...
    def acquire_locks(): # -> None:
        ...
    
    def release_locks(): # -> None:
        ...
    
    def create_logger_lock(): # -> Lock:
        ...
    
    def create_handler_lock(): # -> Lock:
        ...
    
