"""
This type stub file was generated by pyright.
"""

class StreamSink:
    def __init__(self, stream) -> None:
        ...
    
    def write(self, message): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def tasks_to_complete(self): # -> list[Any]:
        ...
    


class StandardSink:
    def __init__(self, handler) -> None:
        ...
    
    def write(self, message): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def tasks_to_complete(self): # -> list[Any]:
        ...
    


class AsyncSink:
    def __init__(self, function, loop, error_interceptor) -> None:
        ...
    
    def write(self, message): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def tasks_to_complete(self): # -> list[Coroutine[Any, Any, None]]:
        ...
    
    def __getstate__(self): # -> dict[str, Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    


class CallableSink:
    def __init__(self, function) -> None:
        ...
    
    def write(self, message): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def tasks_to_complete(self): # -> list[Any]:
        ...
    


