"""
This type stub file was generated by pyright.
"""

class Frequencies:
    @staticmethod
    def hourly(t):
        ...
    
    @staticmethod
    def daily(t):
        ...
    
    @staticmethod
    def weekly(t):
        ...
    
    @staticmethod
    def monthly(t):
        ...
    
    @staticmethod
    def yearly(t):
        ...
    


def parse_size(size): # -> Any | None:
    ...

def parse_duration(duration): # -> timedelta | None:
    ...

def parse_frequency(frequency): # -> Callable[..., Any] | None:
    ...

def parse_day(day): # -> int | None:
    ...

def parse_time(time): # -> _Time | None:
    ...

def parse_daytime(daytime): # -> tuple[int | None, _Time | None] | None:
    ...

