"""
This type stub file was generated by pyright.
"""

from .ask_coder import AskCoder

class ArchitectCoder(AskCoder):
    edit_format = ...
    gpt_prompts = ...
    def reply_completed(self): # -> None:
        ...
    


