"""
This type stub file was generated by pyright.
"""

from .base_coder import Coder

class AskCoder(Coder):
    """Ask questions about code without making any changes."""
    edit_format = ...
    gpt_prompts = ...


