"""
This type stub file was generated by pyright.
"""

from .wholefile_coder import WholeFileCoder

class EditorWholeFileCoder(WholeFileCoder):
    "A coder that operates on entire files, focused purely on editing files."
    edit_format = ...
    gpt_prompts = ...


