"""
This type stub file was generated by pyright.
"""

from .base_coder import Coder

class HelpCoder(Coder):
    """Interactive help and documentation about aider."""
    edit_format = ...
    gpt_prompts = ...
    def get_edits(self, mode=...): # -> list[Any]:
        ...
    
    def apply_edits(self, edits): # -> None:
        ...
    


