"""
This type stub file was generated by pyright.
"""

from .base_prompts import CoderPrompts

class UnifiedDiffPrompts(CoderPrompts):
    main_system = ...
    example_messages = ...
    system_reminder = ...


