"""
This type stub file was generated by pyright.
"""

from typing import Generator, Optional, TYPE_CHECKING, Type, TypeVar
from .abc import Messageable
from types import TracebackType

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    BE = TypeVar('BE', bound=BaseException)
__all__ = ('Typing', )
class Typing:
    def __init__(self, messageable: Messageable) -> None:
        ...
    
    async def wrapped_typer(self) -> None:
        ...
    
    def __await__(self) -> Generator[None, None, None]:
        ...
    
    async def do_typing(self) -> None:
        ...
    
    async def __aenter__(self) -> None:
        ...
    
    async def __aexit__(self, exc_type: Optional[Type[BE]], exc: Optional[BE], traceback: Optional[TracebackType]) -> None:
        ...
    


