"""
This type stub file was generated by pyright.
"""

import requests
import requests.auth

"""OAuth helper functions and classes"""
def nonce(size, alphabet=...): # -> str:
    """Generate a nonce value with 'size' characters"""
    ...

def quote(value, quote=...):
    """Quote 'value' according to the OAuth1.0 standard"""
    ...

def concat(*args): # -> str:
    """Concatenate 'args' as expected by OAuth1.0"""
    ...

class OAuth1Session(requests.Session):
    """Extension to requests.Session to support OAuth 1.0"""
    def __init__(self, consumer_key, consumer_secret, token=..., token_secret=...) -> None:
        ...
    
    def rebuild_auth(self, prepared_request, response): # -> None:
        ...
    


class OAuth1Client(requests.auth.AuthBase):
    """OAuth1.0a authentication"""
    def __init__(self, consumer_key, consumer_secret, token=..., token_secret=...) -> None:
        ...
    
    def __call__(self, request):
        ...
    
    def generate_signature(self, request, params): # -> str:
        """Generate 'oauth_signature' value"""
        ...
    


class OAuth1API:
    """Base class for OAuth1.0 based API interfaces"""
    API_KEY = ...
    API_SECRET = ...
    def __init__(self, extractor) -> None:
        ...
    
    def request(self, url, **kwargs):
        ...
    


