"""
This type stub file was generated by pyright.
"""

"""Helpers for interacting with youtube-dl"""
def import_module(module_name): # -> Any:
    ...

def construct_YoutubeDL(module, obj, user_opts, system_opts=...):
    ...

def parse_command_line(module, argv):
    ...

def parse_retries(retries, name=...): # -> float | int:
    ...

def legacy_postprocessors(opts, module, ytdlp, compat_opts):
    ...

