"""
This type stub file was generated by pyright.
"""

"""Downloader modules"""
modules = ...
def find(scheme): # -> Any | None:
    """Return downloader class suitable for handling the given scheme"""
    ...

_cache = ...
