"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Dict, List

class MessageRole(str, Enum):
    USER = ...
    ASSISTANT = ...
    SYSTEM = ...
    TOOL_CALL = ...
    TOOL_RESPONSE = ...
    @classmethod
    def roles(cls): # -> list[str]:
        ...
    


def get_clean_message_list(message_list: List[Dict[str, str]], role_conversions: Dict[str, str] = ...): # -> list[Any]:
    """
    Subsequent messages with the same role will be concatenated to a single message.

    Args:
        message_list (`List[Dict[str, str]]`): List of chat messages.
    """
    ...

llama_role_conversions = ...
class HfEngine:
    def __init__(self, model: str = ...) -> None:
        ...
    
    def __call__(self, messages: List[Dict[str, str]], stop_sequences=...) -> str:
        ...
    


