"""
This type stub file was generated by pyright.
"""

class FPS:
	def __init__(self) -> None:
		...
	
	def start(self): # -> Self:
		...
	
	def stop(self): # -> None:
		...
	
	def update(self): # -> None:
		...
	
	def elapsed(self): # -> float:
		...
	
	def fps(self): # -> float:
		...
	


