"""
This type stub file was generated by pyright.
"""

"""
Exceptions factored out to avoid import loops.
"""
class DropEvent(BaseException):
    """
    If raised by an processor, the event gets silently dropped.

    Derives from BaseException because it's technically not an error.
    """
    ...


