"""
This type stub file was generated by pyright.
"""

"""
Deprecated name for :mod:`structlog.typing`.

.. versionadded:: 20.2.0
.. deprecated:: 22.2.0
"""
__all__ = ("WrappedLogger", "Context", "EventDict", "Processor", "ExcInfo", "ExceptionRenderer", "ExceptionTransformer", "BindableLogger", "FilteringBoundLogger")
