"""
This type stub file was generated by pyright.
"""

from .configuration_utils import PretrainedConfig
from .utils import is_torch_available

logger = ...
if is_torch_available():
    ...
ROPE_INIT_FUNCTIONS = ...
ROPE_VALIDATION_FUNCTIONS = ...
def rope_config_validation(config: PretrainedConfig): # -> None:
    """
    Validate the RoPE config arguments, given a `PretrainedConfig` object
    """
    ...

