"""
This type stub file was generated by pyright.
"""

from stone.backends.python_rsrc import stone_base as bb

"""
This namespace contains endpoints and data types for user management.
"""
class Account(bb.Struct):
    """
    The amount of detail revealed about an account depends on the user being
    queried and the user making the query.

    :ivar users.Account.account_id: The user's unique Dropbox ID.
    :ivar users.Account.name: Details of a user's name.
    :ivar users.Account.email: The user's email address. Do not rely on this
        without checking the ``email_verified`` field. Even then, it's possible
        that the user has since lost access to their email.
    :ivar users.Account.email_verified: Whether the user has verified their
        email address.
    :ivar users.Account.profile_photo_url: URL for the photo representing the
        user, if one is set.
    :ivar users.Account.disabled: Whether the user has been disabled.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, account_id=..., name=..., email=..., email_verified=..., disabled=..., profile_photo_url=...) -> None:
        ...
    
    account_id = ...
    name = ...
    email = ...
    email_verified = ...
    profile_photo_url = ...
    disabled = ...


Account_validator = ...
class BasicAccount(Account):
    """
    Basic information about any account.

    :ivar users.BasicAccount.is_teammate: Whether this user is a teammate of the
        current user. If this account is the current user's account, then this
        will be ``True``.
    :ivar users.BasicAccount.team_member_id: The user's unique team member id.
        This field will only be present if the user is part of a team and
        ``is_teammate`` is ``True``.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, account_id=..., name=..., email=..., email_verified=..., disabled=..., is_teammate=..., profile_photo_url=..., team_member_id=...) -> None:
        ...
    
    is_teammate = ...
    team_member_id = ...


BasicAccount_validator = ...
class FileLockingValue(bb.Union):
    """
    The value for ``UserFeature.file_locking``.

    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.

    :ivar bool users.FileLockingValue.enabled: When this value is True, the user
        can lock files in shared directories. When the value is False the user
        can unlock the files they have locked or request to unlock files locked
        by others.
    """
    _catch_all = ...
    other = ...
    @classmethod
    def enabled(cls, val): # -> Self:
        """
        Create an instance of this class set to the ``enabled`` tag with value
        ``val``.

        :param bool val:
        :rtype: FileLockingValue
        """
        ...
    
    def is_enabled(self):
        """
        Check if the union tag is ``enabled``.

        :rtype: bool
        """
        ...
    
    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        ...
    
    def get_enabled(self): # -> None:
        """
        When this value is True, the user can lock files in shared directories.
        When the value is False the user can unlock the files they have locked
        or request to unlock files locked by others.

        Only call this if :meth:`is_enabled` is true.

        :rtype: bool
        """
        ...
    


FileLockingValue_validator = ...
class FullAccount(Account):
    """
    Detailed information about the current user's account.

    :ivar users.FullAccount.country: The user's two-letter country code, if
        available. Country codes are based on `ISO 3166-1
        <http://en.wikipedia.org/wiki/ISO_3166-1>`_.
    :ivar users.FullAccount.locale: The language that the user specified. Locale
        tags will be `IETF language tags
        <http://en.wikipedia.org/wiki/IETF_language_tag>`_.
    :ivar users.FullAccount.referral_link: The user's `referral link
        <https://www.dropbox.com/referrals>`_.
    :ivar users.FullAccount.team: If this account is a member of a team,
        information about that team.
    :ivar users.FullAccount.team_member_id: This account's unique team member
        id. This field will only be present if ``team`` is present.
    :ivar users.FullAccount.is_paired: Whether the user has a personal and work
        account. If the current account is personal, then ``team`` will always
        be None, but ``is_paired`` will indicate if a work account is linked.
    :ivar users.FullAccount.account_type: What type of account this user has.
    :ivar users.FullAccount.root_info: The root info for this account.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, account_id=..., name=..., email=..., email_verified=..., disabled=..., locale=..., referral_link=..., is_paired=..., account_type=..., root_info=..., profile_photo_url=..., country=..., team=..., team_member_id=...) -> None:
        ...
    
    country = ...
    locale = ...
    referral_link = ...
    team = ...
    team_member_id = ...
    is_paired = ...
    account_type = ...
    root_info = ...


FullAccount_validator = ...
class Team(bb.Struct):
    """
    Information about a team.

    :ivar users.Team.id: The team's unique ID.
    :ivar users.Team.name: The name of the team.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, id=..., name=...) -> None:
        ...
    
    id = ...
    name = ...


Team_validator = ...
class FullTeam(Team):
    """
    Detailed information about a team.

    :ivar users.FullTeam.sharing_policies: Team policies governing sharing.
    :ivar users.FullTeam.office_addin_policy: Team policy governing the use of
        the Office Add-In.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, id=..., name=..., sharing_policies=..., office_addin_policy=...) -> None:
        ...
    
    sharing_policies = ...
    office_addin_policy = ...


FullTeam_validator = ...
class GetAccountArg(bb.Struct):
    """
    :ivar users.GetAccountArg.account_id: A user's account identifier.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, account_id=...) -> None:
        ...
    
    account_id = ...


GetAccountArg_validator = ...
class GetAccountBatchArg(bb.Struct):
    """
    :ivar users.GetAccountBatchArg.account_ids: List of user account
        identifiers.  Should not contain any duplicate account IDs.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, account_ids=...) -> None:
        ...
    
    account_ids = ...


GetAccountBatchArg_validator = ...
class GetAccountBatchError(bb.Union):
    """
    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.

    :ivar str users.GetAccountBatchError.no_account: The value is an account ID
        specified in :field:`GetAccountBatchArg.account_ids` that does not
        exist.
    """
    _catch_all = ...
    other = ...
    @classmethod
    def no_account(cls, val): # -> Self:
        """
        Create an instance of this class set to the ``no_account`` tag with
        value ``val``.

        :param str val:
        :rtype: GetAccountBatchError
        """
        ...
    
    def is_no_account(self):
        """
        Check if the union tag is ``no_account``.

        :rtype: bool
        """
        ...
    
    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        ...
    
    def get_no_account(self): # -> None:
        """
        The value is an account ID specified in
        ``GetAccountBatchArg.account_ids`` that does not exist.

        Only call this if :meth:`is_no_account` is true.

        :rtype: str
        """
        ...
    


GetAccountBatchError_validator = ...
class GetAccountError(bb.Union):
    """
    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.

    :ivar users.GetAccountError.no_account: The specified
        ``GetAccountArg.account_id`` does not exist.
    """
    _catch_all = ...
    no_account = ...
    other = ...
    def is_no_account(self):
        """
        Check if the union tag is ``no_account``.

        :rtype: bool
        """
        ...
    
    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        ...
    


GetAccountError_validator = ...
class IndividualSpaceAllocation(bb.Struct):
    """
    :ivar users.IndividualSpaceAllocation.allocated: The total space allocated
        to the user's account (bytes).
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, allocated=...) -> None:
        ...
    
    allocated = ...


IndividualSpaceAllocation_validator = ...
class Name(bb.Struct):
    """
    Representations for a person's name to assist with internationalization.

    :ivar users.Name.given_name: Also known as a first name.
    :ivar users.Name.surname: Also known as a last name or family name.
    :ivar users.Name.familiar_name: Locale-dependent name. In the US, a person's
        familiar name is their ``given_name``, but elsewhere, it could be any
        combination of a person's ``given_name`` and ``surname``.
    :ivar users.Name.display_name: A name that can be used directly to represent
        the name of a user's Dropbox account.
    :ivar users.Name.abbreviated_name: An abbreviated form of the person's name.
        Their initials in most locales.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, given_name=..., surname=..., familiar_name=..., display_name=..., abbreviated_name=...) -> None:
        ...
    
    given_name = ...
    surname = ...
    familiar_name = ...
    display_name = ...
    abbreviated_name = ...


Name_validator = ...
class PaperAsFilesValue(bb.Union):
    """
    The value for ``UserFeature.paper_as_files``.

    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.

    :ivar bool users.PaperAsFilesValue.enabled: When this value is true, the
        user's Paper docs are accessible in Dropbox with the .paper extension
        and must be accessed via the /files endpoints.  When this value is
        false, the user's Paper docs are stored separate from Dropbox files and
        folders and should be accessed via the /paper endpoints.
    """
    _catch_all = ...
    other = ...
    @classmethod
    def enabled(cls, val): # -> Self:
        """
        Create an instance of this class set to the ``enabled`` tag with value
        ``val``.

        :param bool val:
        :rtype: PaperAsFilesValue
        """
        ...
    
    def is_enabled(self):
        """
        Check if the union tag is ``enabled``.

        :rtype: bool
        """
        ...
    
    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        ...
    
    def get_enabled(self): # -> None:
        """
        When this value is true, the user's Paper docs are accessible in Dropbox
        with the .paper extension and must be accessed via the /files endpoints.
        When this value is false, the user's Paper docs are stored separate from
        Dropbox files and folders and should be accessed via the /paper
        endpoints.

        Only call this if :meth:`is_enabled` is true.

        :rtype: bool
        """
        ...
    


PaperAsFilesValue_validator = ...
class SpaceAllocation(bb.Union):
    """
    Space is allocated differently based on the type of account.

    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.

    :ivar IndividualSpaceAllocation SpaceAllocation.individual: The user's space
        allocation applies only to their individual account.
    :ivar TeamSpaceAllocation SpaceAllocation.team: The user shares space with
        other members of their team.
    """
    _catch_all = ...
    other = ...
    @classmethod
    def individual(cls, val): # -> Self:
        """
        Create an instance of this class set to the ``individual`` tag with
        value ``val``.

        :param IndividualSpaceAllocation val:
        :rtype: SpaceAllocation
        """
        ...
    
    @classmethod
    def team(cls, val): # -> Self:
        """
        Create an instance of this class set to the ``team`` tag with value
        ``val``.

        :param TeamSpaceAllocation val:
        :rtype: SpaceAllocation
        """
        ...
    
    def is_individual(self):
        """
        Check if the union tag is ``individual``.

        :rtype: bool
        """
        ...
    
    def is_team(self):
        """
        Check if the union tag is ``team``.

        :rtype: bool
        """
        ...
    
    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        ...
    
    def get_individual(self): # -> None:
        """
        The user's space allocation applies only to their individual account.

        Only call this if :meth:`is_individual` is true.

        :rtype: IndividualSpaceAllocation
        """
        ...
    
    def get_team(self): # -> None:
        """
        The user shares space with other members of their team.

        Only call this if :meth:`is_team` is true.

        :rtype: TeamSpaceAllocation
        """
        ...
    


SpaceAllocation_validator = ...
class SpaceUsage(bb.Struct):
    """
    Information about a user's space usage and quota.

    :ivar users.SpaceUsage.used: The user's total space usage (bytes).
    :ivar users.SpaceUsage.allocation: The user's space allocation.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, used=..., allocation=...) -> None:
        ...
    
    used = ...
    allocation = ...


SpaceUsage_validator = ...
class TeamSpaceAllocation(bb.Struct):
    """
    :ivar users.TeamSpaceAllocation.used: The total space currently used by the
        user's team (bytes).
    :ivar users.TeamSpaceAllocation.allocated: The total space allocated to the
        user's team (bytes).
    :ivar users.TeamSpaceAllocation.user_within_team_space_allocated: The total
        space allocated to the user within its team allocated space (0 means
        that no restriction is imposed on the user's quota within its team).
    :ivar users.TeamSpaceAllocation.user_within_team_space_limit_type: The type
        of the space limit imposed on the team member (off, alert_only,
        stop_sync).
    :ivar users.TeamSpaceAllocation.user_within_team_space_used_cached: An
        accurate cached calculation of a team member's total space usage
        (bytes).
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, used=..., allocated=..., user_within_team_space_allocated=..., user_within_team_space_limit_type=..., user_within_team_space_used_cached=...) -> None:
        ...
    
    used = ...
    allocated = ...
    user_within_team_space_allocated = ...
    user_within_team_space_limit_type = ...
    user_within_team_space_used_cached = ...


TeamSpaceAllocation_validator = ...
class UserFeature(bb.Union):
    """
    A set of features that a Dropbox User account may have configured.

    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.

    :ivar users.UserFeature.paper_as_files: This feature contains information
        about how the user's Paper files are stored.
    :ivar users.UserFeature.file_locking: This feature allows users to lock
        files in order to restrict other users from editing them.
    """
    _catch_all = ...
    paper_as_files = ...
    file_locking = ...
    other = ...
    def is_paper_as_files(self):
        """
        Check if the union tag is ``paper_as_files``.

        :rtype: bool
        """
        ...
    
    def is_file_locking(self):
        """
        Check if the union tag is ``file_locking``.

        :rtype: bool
        """
        ...
    
    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        ...
    


UserFeature_validator = ...
class UserFeatureValue(bb.Union):
    """
    Values that correspond to entries in :class:`UserFeature`.

    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.
    """
    _catch_all = ...
    other = ...
    @classmethod
    def paper_as_files(cls, val): # -> Self:
        """
        Create an instance of this class set to the ``paper_as_files`` tag with
        value ``val``.

        :param PaperAsFilesValue val:
        :rtype: UserFeatureValue
        """
        ...
    
    @classmethod
    def file_locking(cls, val): # -> Self:
        """
        Create an instance of this class set to the ``file_locking`` tag with
        value ``val``.

        :param FileLockingValue val:
        :rtype: UserFeatureValue
        """
        ...
    
    def is_paper_as_files(self):
        """
        Check if the union tag is ``paper_as_files``.

        :rtype: bool
        """
        ...
    
    def is_file_locking(self):
        """
        Check if the union tag is ``file_locking``.

        :rtype: bool
        """
        ...
    
    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        ...
    
    def get_paper_as_files(self): # -> None:
        """
        Only call this if :meth:`is_paper_as_files` is true.

        :rtype: PaperAsFilesValue
        """
        ...
    
    def get_file_locking(self): # -> None:
        """
        Only call this if :meth:`is_file_locking` is true.

        :rtype: FileLockingValue
        """
        ...
    


UserFeatureValue_validator = ...
class UserFeaturesGetValuesBatchArg(bb.Struct):
    """
    :ivar users.UserFeaturesGetValuesBatchArg.features: A list of features in
        :class:`UserFeature`. If the list is empty, this route will return
        :class:`UserFeaturesGetValuesBatchError`.
    """
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, features=...) -> None:
        ...
    
    features = ...


UserFeaturesGetValuesBatchArg_validator = ...
class UserFeaturesGetValuesBatchError(bb.Union):
    """
    This class acts as a tagged union. Only one of the ``is_*`` methods will
    return true. To get the associated value of a tag (if one exists), use the
    corresponding ``get_*`` method.

    :ivar users.UserFeaturesGetValuesBatchError.empty_features_list: At least
        one :class:`UserFeature` must be included in the
        :class:`UserFeaturesGetValuesBatchArg`.features list.
    """
    _catch_all = ...
    empty_features_list = ...
    other = ...
    def is_empty_features_list(self):
        """
        Check if the union tag is ``empty_features_list``.

        :rtype: bool
        """
        ...
    
    def is_other(self):
        """
        Check if the union tag is ``other``.

        :rtype: bool
        """
        ...
    


UserFeaturesGetValuesBatchError_validator = ...
class UserFeaturesGetValuesBatchResult(bb.Struct):
    __slots__ = ...
    _has_required_fields = ...
    def __init__(self, values=...) -> None:
        ...
    
    values = ...


UserFeaturesGetValuesBatchResult_validator = ...
GetAccountBatchResult_validator = ...
features_get_values = ...
get_account = ...
get_account_batch = ...
get_current_account = ...
get_space_usage = ...
ROUTES = ...
