"""
This type stub file was generated by pyright.
"""

from typing import Any, List

import torch

@torch.jit.unused
def to_tensor(inpt: Any) -> torch.Tensor:
    """[DEPREACTED] Use to_image() and to_dtype() instead."""
    ...

def get_image_size(inpt: torch.Tensor) -> List[int]:
    ...
