"""
This type stub file was generated by pyright.
"""

import sys
import re

modules = ...
def find(url): # -> None:
    """Find a suitable extractor for the given URL"""
    ...

def add(cls):
    """Add 'cls' to the list of available extractors"""
    ...

def add_module(module): # -> list[Any]:
    """Add all extractors in 'module' to the list of available extractors"""
    ...

def extractors(): # -> list[Any]:
    """Yield all available extractor classes"""
    ...

_cache = ...
_module_iter = ...
