"""
This type stub file was generated by pyright.
"""

from ..convenience import is_cv2

if is_cv2():
    def FeatureDetector_create(method): # -> DENSE | GFTT | HARRIS:
        ...
    
    def DescriptorExtractor_create(method): # -> RootSIFT:
        ...
    
    def DescriptorMatcher_create(method):
        ...
    
else:
    _DETECTOR_FACTORY = ...
    _EXTRACTOR_FACTORY = ...
    _MATCHER_FACTORY = ...
    _CONTRIB_FUNCS = ...
    def FeatureDetector_create(detector, *args, **kw_args):
        """

        :param detector: string of the type of keypoint detector to return
        :param args: positional arguments for detector
        :param kw_args: keyword arguments for detector
        :return: the key point detector object
        """
        ...
    
    def DescriptorExtractor_create(extractor, *args, **kw_args):
        """

        :param extractor: string of the type of descriptor extractor to return
        :param args: positional arguments for extractor
        :param kw_args: keyword arguments for extractor
        :return: the key extractor object
        """
        ...
    
    def DescriptorMatcher_create(matcher):
        """

        :param matcher: string of the type of descriptor matcher to return
        :return: the matcher int
        """
        ...
    
