"""
This type stub file was generated by pyright.
"""


'''
PySnooper - Never use print for debugging again

Usage:

    import pysnooper

    @pysnooper.snoop()
    def your_function(x):
        ...

A log will be written to stderr showing the lines executed and variables
changed in the decorated function.

For more information, see https://github.com/cool-RR/PySnooper
'''
__VersionInfo = ...
__version__ = ...
__version_info__ = ...
